Repository boostcampwm-2022/web06-weview, pull requests merged in 2022-11, with the labels that each got.

#14 FE Cypress 테스트 환경 구축 (#8)
  client/.eslintrc.json
  client/cypress.config.ts
  client/cypress/e2e/spec.cy.ts
  client/cypress/fixtures/example.json
  client/cypress/support/commands.ts
  client/cypress/support/e2e.ts
  client/cypress/support/index.ts
  client/package-lock.json
  client/package.json
  client/tsconfig.json
Labels: ⚙ Setting

#15 FE Jest 테스트 환경 구축 (#8)
  client/jest.config.js
  client/package-lock.json
  client/package.json
Labels: ⚙ Setting

#17 FE react query 세팅 및 환경 구축 (#11)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
Labels: ⚙ Setting

#34 README.md 추가 및 내용 작성 (#33)
  README.md
Labels: 📃 Docs

#39 Fix/#38 fix ci error
  .github/workflows/client-integration.yml
  .github/workflows/server-integration.yml
Labels: 🐞 BugFix

#45 Database 연결 (#43)
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/base-time.entity.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/user/user.entity.ts
Labels: ✨ Feature

#48 FE 로그아웃 API 적용 및 Mock API 설정 (#19)
  client/src/components/Profile/UserProfile/UserProfile.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/authHandler.ts
  client/src/utils/localStorage.ts
Labels: ✨ Feature, 🔨 Refactor

#51 react query 사용한 hook들 test하기 위한 환경 설정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.scss
  client/src/App.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/react-query/queryClient.ts
  client/src/react-query/queryKeys.ts
  client/src/test-utils/rq.tsx
  client/src/utils/typeCheck.ts
Labels: ⚙ Setting, ✅ Test

#52 로그인 팝업 호출 시 발생하는 cross-origin 오류 해결 및 라우팅 적용 (#49)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/ReactRouter.tsx
  client/src/components/LoginCallback/LoginCallback.scss
  client/src/components/LoginCallback/LoginCallback.tsx
  client/src/components/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
  client/src/hooks/useOAuthPopup.tsx
Labels: ✨ Feature, 🐞 BugFix

#55 github oauth를 axios 라이브러리로 구현했습니다.
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
Labels: ✨ Feature

#65 서버 테스트 코드가 실행되지 않는 버그 수정
  server/src/app.controller.spec.ts
  server/src/domain/auth/auth.controller.spec.ts
  server/src/domain/auth/auth.service.spec.ts
Labels: 🐞 BugFix

#68 API 명세 변경에 따라 서버 리턴값을 변경했습니다.
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/auth/dto/controller-response.dto.ts
  server/src/domain/base-time.entity.ts
Labels: 🔨 Refactor

#70 게시물 엔티티 구조를 생성했습니다.
  server/src/domain/post/post.controller.spec.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
Labels: ✨ Feature

#75 로그아웃, 토큰 갱신에 대한 e2e 테스트를 작성했습니다.
  server/package-lock.json
  server/package.json
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/base-time.entity.ts
  server/test/app.e2e-spec.ts
  server/test/auth.e2e-spec.ts
Labels: ✅ Test

#71 기본적인 인피니티 스크롤 로딩 구현 (#60)
  client/src/ReactRouter.tsx
  client/src/apis/post.ts
  client/src/components/PostBar/Post/Post.scss
  client/src/components/PostBar/Post/Post.tsx
  client/src/components/PostBar/PostBar.scss
  client/src/components/PostBar/PostBar.tsx
  client/src/hooks/useIntersect.tsx
  client/src/hooks/usePostInfiniteScroll.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/mockData.ts
  client/src/pages/Main.tsx
  client/src/types/post.ts
Labels: ✨ Feature

#66 글쓰기 모달 레이아웃
  client/.husky/pre-commit
  client/constants/_library.scss
  client/src/App.scss
  client/src/ReactRouter.tsx
  client/src/components/CommonButtons/CommonButtons.scss
  client/src/components/MainNav/Filter/Filter.scss
  client/src/components/MainNav/Filter/Filter.tsx
  client/src/components/MainNav/MainNav.scss
  client/src/components/MainNav/MainNav.tsx
  client/src/components/MainNav/Menu/Menu.scss
  client/src/components/MainNav/Menu/Menu.tsx
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.scss
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
  client/src/components/MainNav/Profile/Profile.scss
  client/src/components/MainNav/Profile/Profile.tsx
  client/src/components/MainNav/Profile/UserProfile/UserProfile.scss
  client/src/components/MainNav/Profile/UserProfile/UserProfile.tsx
  client/src/components/WriteModal/CloseButton/CloseButton.scss
  client/src/components/WriteModal/CloseButton/CloseButton.tsx
  client/src/components/WriteModal/SnapShotNav/SnapShotNav.scss
  client/src/components/WriteModal/SnapShotNav/SnapShotNav.tsx
  client/src/components/WriteModal/WriteModal.scss
  client/src/components/WriteModal/WriteModal.tsx
  client/src/components/WriteModal/WritingForm/CodeEditor/CodeEditor.scss
  client/src/components/WriteModal/WritingForm/CodeEditor/CodeEditor.tsx
  client/src/components/WriteModal/WritingForm/PrettifyButton/PrettifyButton.scss
  client/src/components/WriteModal/WritingForm/PrettifyButton/PrettifyButton.tsx
  client/src/components/WriteModal/WritingForm/SubmitButton/SubmitButton.scss
  client/src/components/WriteModal/WritingForm/SubmitButton/SubmitButton.tsx
  client/src/components/WriteModal/WritingForm/TitleInput/TitleInput.scss
  client/src/components/WriteModal/WritingForm/TitleInput/TitleInput.tsx
  client/src/components/WriteModal/WritingForm/WritingForm.scss
  client/src/components/WriteModal/WritingForm/WritingForm.tsx
  client/src/pages/LoginCallback/LoginCallback.scss
  client/src/pages/LoginCallback/LoginCallback.tsx
  client/src/pages/Main.tsx
  client/src/store/useModalStore.ts
  client/src/store/useWritingStore.ts
Labels: 🎨 Html&css

#80 인피니티 스크롤(PostBar 컴포넌트) 세부 레이아웃 및 뷰 로직 구현 (#60)
  client/src/App.scss
  client/src/components/PostBar/Post/Post.scss
  client/src/components/PostBar/Post/Post.tsx
  client/src/components/PostBar/Post/PostBody/PostBody.tsx
  client/src/components/PostBar/Post/PostFooter/LikeButton/LikeButton.tsx
  client/src/components/PostBar/Post/PostFooter/MoreButton/MoreButton.tsx
  client/src/components/PostBar/Post/PostFooter/PostFooter.tsx
  client/src/components/PostBar/Post/PostFooter/ReportButton/ReportButton.tsx
  client/src/components/PostBar/Post/PostFooter/ReviewButton/ReviewButton.tsx
  client/src/components/PostBar/Post/PostFooter/ShareButton/ShareButton.tsx
  client/src/components/PostBar/Post/PostImageSlider/PostImageSlider.tsx
  client/src/components/PostBar/Post/PostSummary/CodeInfo/CodeInfo.tsx
  client/src/components/PostBar/Post/PostSummary/PostSummary.tsx
  client/src/components/PostBar/Post/PostTitle/AuthorProfile/AuthorProfile.tsx
  client/src/components/PostBar/Post/PostTitle/PostTitle.tsx
  client/src/components/PostBar/Post/PostTitle/TimeStamp/TimeStamp.tsx
  client/src/components/PostBar/PostBar.scss
  client/src/components/PostBar/PostBar.tsx
  client/src/hooks/useRelativeSize.tsx
  client/src/mocks/handlers/postHandler.ts
  client/src/utils/timeUtils.ts
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#81 dev main 브랜치 push 방지용 pre-push 훅 설정
  client/.husky/pre-push
  client/package.json
  server/.husky/pre-push
  server/package.json
Labels: ⚙ Setting

#87 백엔드 글 작성 기능을 구현했습니다.
  server/src/app.module.ts
  server/src/domain/auth/access-token.strategy.ts
  server/src/domain/auth/dto/controller-request.dto.ts
  server/src/domain/image/image.entity.ts
  server/src/domain/post/post.controller.spec.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/tag/post-to-tag.entity.ts
  server/src/domain/tag/tag.entity.ts
  server/src/main.ts
Labels: ✨ Feature

#98 글 작성 기능에 대한 e2e 테스트를 작성했습니다.
  server/package.json
  server/src/domain/auth/auth.module.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.service.spec.ts
  server/test/auth.e2e-spec.ts
  server/test/post.e2e-spec.ts
Labels: ✅ Test

#102 (2차) 게시물 목록을 조회하는 기능을 구현했습니다.
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.service.ts
Labels: ✨ Feature

#105 fix(DO): 도커 이미지 업로드에서 husky 동작하는 버그 수정 (#104)
  server/Dockerfile
Labels: 🐞 BugFix

#106 ci(DO): 환경변수 주입 (#104)
  .github/workflows/dev-client-deploy.yml
Labels: 🌏 Deploy

#112 fix(BE): 글 목록 조회 API 스펙 클라이언트와 동기화 (#111)
  server/src/domain/post/dto/service-response.dto.ts
Labels: 🐞 BugFix

#116 fix(FE): axios authorization header에 Bearer 추가 (#113)
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
Labels: 🐞 BugFix

#119 fix(BE): 태그가 없을 때 글 작성 실패하는 버그 수정 (#118)
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#121 배포 오류 수정 후 dev 브랜치에서 main 브랜치로 병합
  .github/workflows/dev-client-deploy.yml
  client/.gitignore
  client/src/apis/axios.ts
  client/src/apis/post.ts
  client/src/components/LoadingSpinner/LoadingSpinner.scss
  client/src/components/LoadingSpinner/LoadingSpinner.tsx
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
  client/src/components/MainNav/Profile/UserProfile/UserProfile.tsx
  client/src/components/PostBar/Post/PostImageSlider/PostImageSlider.tsx
  client/src/components/PostBar/Post/PostSummary/CodeInfo/CodeInfo.tsx
  client/src/components/PostBar/Post/PostTitle/AuthorProfile/AuthorProfile.tsx
  client/src/constants/env.ts
  client/src/hooks/useOAuthPopup.tsx
  client/src/hooks/usePostInfiniteScroll.tsx
  client/src/main.tsx
  client/src/mocks/handlers/authHandler.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/mockData.ts
  client/src/pages/LoginCallback/LoginCallback.tsx
  client/src/store/useAuthStore.ts
  client/src/types/auth.ts
  client/src/types/post.ts
  server/Dockerfile
  server/src/domain/auth/auth.controller.ts
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.service.ts
Labels: 🌏 Deploy

#129 사용자 정의 예외 및 리뷰 작성 기능을 구현했습니다. (#90)
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/review/dto/controller-request.dto.ts
  server/src/domain/review/review.controller.ts
  server/src/domain/review/review.entity.ts
  server/src/domain/review/review.module.ts
  server/src/domain/review/review.service.ts
  server/src/exception/post-not-found.exception.ts
  server/src/exception/user-not-found.exception.ts
  server/src/main.ts
Labels: ✨ Feature

#130 게시물을 조회하는 로직에 대해 리팩토링을 진행했습니다.
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/auth/auth.controller.ts
  server/src/domain/image/image.entity.ts
  server/src/domain/post-to-tag/post-to-tag.entity.ts
  server/src/domain/post-to-tag/post-to-tag.repository.ts
  server/src/domain/post/category.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/service-request.dto.ts
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/tag/tag.entity.ts
  server/src/domain/tag/tag.repository.ts
  server/src/main.ts
  server/src/typeorm/typeorm-ex.decorator.ts
  server/src/typeorm/typeorm-ex.module.ts
  server/test/auth.e2e-spec.ts
  server/test/post.e2e-spec.ts
Labels: 🔨 Refactor

#132 포스트바 로딩 컴포넌트 추가 및 레이아웃 크기 고정 (#86)
  client/src/components/LoadingSpinner/LoadingSpinner.tsx
  client/src/components/MainNav/MainNav.scss
  client/src/components/PostBar/Post/Post.scss
  client/src/components/PostBar/Post/Post.tsx
  client/src/components/PostBar/PostBar.scss
  client/src/components/PostBar/PostBar.tsx
  client/src/components/PostBar/PostLoader/PostLoader.scss
  client/src/components/PostBar/PostLoader/PostLoader.tsx
  client/src/hooks/usePostInfiniteScroll.tsx
  client/src/pages/Main/Main.scss
  client/src/styles/commons/_global-styles.scss
  client/src/styles/commons/_responsive.scss
Labels: 🎨 Html&css, 🥰 Accessibility

#139 검색 기능을 구현한다
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/service-request.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/test/post.e2e-spec.ts
Labels: ✨ Feature

#138 검색 기능 구현 (#137)
  client/src/App.scss
  client/src/App.tsx
  client/src/components/MainNav/Filter/Filter.scss
  client/src/components/MainNav/Filter/Filter.tsx
  client/src/components/MainNav/Filter/SearchModal/SearchModal.scss
  client/src/components/MainNav/Filter/SearchModal/SearchModal.tsx
  client/src/components/MainNav/MainNav.tsx
  client/src/components/MainNav/Menu/Menu.scss
  client/src/components/MainNav/Profile/Profile.scss
  client/src/components/ModalContainer/ModalContainer.scss
  client/src/components/ModalContainer/ModalContainer.tsx
  client/src/components/WriteModal/SubmitModal/SubmitModal.scss
  client/src/components/WriteModal/WriteModal.scss
  client/src/components/WriteModal/WriteModal.tsx
  client/src/pages/Main/Main.scss
  client/src/store/useAuthStore.ts
  client/src/store/useModalStore.ts
  client/src/styles/commons/_global-styles.scss
Labels: ✨ Feature, 🎨 Html&css, 🥰 Accessibility

#149 인증 및 글 작성 기능에 대한 리팩토링을 진행했습니다.
  server/package.json
  server/src/app.module.ts
  server/src/domain/auth/access-token.strategy.ts
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/auth.service.spec.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/image/image.entity.ts
  server/src/domain/post-to-tag/post-to-tag.repository.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/tag/tag.repository.ts
  server/src/domain/user/user.entity.ts
  server/src/domain/user/user.repository.ts
  server/src/exception/post-not-written.exception.ts
  server/test/auth.e2e-spec.ts
  server/test/jest-e2e.json
  server/test/post.e2e-spec.ts
Labels: 🔨 Refactor

#148 Search Modal 세부 레이아웃 구현 (#137)
  client/src/components/ModalContainer/SearchModal/SearchForm/SearchForm.scss
  client/src/components/ModalContainer/SearchModal/SearchForm/SearchForm.tsx
  client/src/components/ModalContainer/SearchModal/SearchForm/SearchLabel/SearchLabel.tsx
  client/src/components/ModalContainer/SearchModal/SearchModal.scss
  client/src/components/ModalContainer/SearchModal/SearchModal.tsx
  client/src/constants/search.ts
  client/src/types/post.ts
Labels: 🎨 Html&css

#141 좋아요, 좋아요 취소 기능 구현
  server/src/domain/likes/likes.entity.ts
  server/src/domain/likes/likes.repository.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/post/post.subscriber.ts
Labels: ✨ Feature

#155 API 명세 변경에 따른 게시물 목록 조회 파라미터 수정
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/service-request.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/test/post.e2e-spec.ts
Labels: 🔨 Refactor

#165 Root 디렉토리의 package.lock.json을 삭제했습니다.
  package-lock.json
Labels: 🐞 BugFix

#160 글 작성시 태그와 이미지에 대한 필터링을 수정했습니다.
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#154 husky 린트 에러 수정
  client/.husky/commit-msg
  client/package.json
  server/.husky/commit-msg
  server/package.json
Labels: 🐞 BugFix

#162 검색 시 필요없는 내용은 보내지 않게 수정하였습니다.
  client/src/utils/queryString.ts
  client/src/utils/typeCheck.ts
Labels: ✨ Feature

#169 검색 시 태그, 사용자 파라미터의 형태를 변경
  server/src/domain/post/dto/controller-request.dto.ts
  server/test/post.e2e-spec.ts
Labels: 🐞 BugFix

#171 fix(FE): 제출 usecallback 디펜던시에 tags 추가 (#170)
  client/src/components/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
Labels: 🐞 BugFix

#172 test(FE): 검색 필터 MOCK API 추가 및 적용 (#137)
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/utils/postUtils.ts
  client/src/types/post.ts
Labels: ✅ Test

#175 클라이언트 css, scss 프리티파이 (#174)
  client/package.json
Labels: 🌏 Deploy

#178 불필요한 JoinColumn을 삭제했습니다.
  server/src/domain/post-to-tag/post-to-tag.entity.ts
  server/src/domain/post-to-tag/post-to-tag.repository.ts
Labels: 🔨 Refactor

#182 좋아요 기능을 구현했습니다
  server/src/app.module.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/likes/likes.controller.ts
  server/src/domain/likes/likes.module.ts
  server/src/domain/likes/likes.service.ts
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/test/post.e2e-spec.ts
Labels: ✨ Feature

#181 코드 줄 수 관련 로직과 스크롤 관련 로직이 추가됐습니다.
  client/package.json
  client/src/App.scss
  client/src/App.tsx
  client/src/components/Modal/ModalWrapper/CommonModalWrapper.tsx
  client/src/components/Modal/ModalWrapper/ModalWrapper.scss
  client/src/components/Modal/ModalWrapper/OtherModalWrapper.tsx
  client/src/components/Modal/WriteModal/SnapShotNav/SnapShotNav.scss
  client/src/components/Modal/WriteModal/WritingForm/CodeEditor/CodeEditor.scss
  client/src/components/Modal/WriteModal/WritingForm/CodeEditor/CodeEditor.tsx
  client/src/components/Modal/WriteModal/WritingForm/WritingForm.scss
  client/src/hooks/useLineNumbers.tsx
  client/src/styles/_global-styles.scss
Labels: ✨ Feature, 🔨 Refactor

#184 리뷰 관련 훅과 리팩터링
  client/src/apis/auth.ts
  client/src/apis/review.ts
  client/src/hooks/usePostInfiniteScroll.tsx
  client/src/hooks/useReviewInfiniteScroll.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/authHandler.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/handlers/reviewHandler.ts
  client/src/mocks/mockData.ts
  client/src/mocks/utils/postUtils.ts
  client/src/react-query/queryKeys.ts
  client/src/store/useAuthStore.ts
  client/src/types/auth.ts
  client/src/types/post.ts
  client/src/types/review.ts
Labels: ✨ Feature, 🔨 Refactor

#186 백엔드 리뷰 목록 조회 기능을 구현했습니다.
  server/src/domain/review/dto/controller-request.dto.ts
  server/src/domain/review/dto/controller-response.dto.ts
  server/src/domain/review/review.controller.ts
  server/src/domain/review/review.module.ts
  server/src/domain/review/review.repository.ts
  server/src/domain/review/review.service.ts
Labels: ✨ Feature

#188 리뷰 작성 컴포넌트 구현 및 리뷰 Post 요청 API 적용 (#147)
  client/src/apis/review.ts
  client/src/components/CommonButtons/CommonButtons.scss
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewContainer.tsx
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/NotLoggedInReviewForm.tsx
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/ReviewForm.scss
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/ReviewForm.tsx
  client/src/components/Modal/ReviewModal/ReviewModal.scss
  client/src/hooks/useOAuthPopup.tsx
  client/src/types/review.ts
Labels: ✨ Feature

#189 리뷰 목록 구현
  client/src/apis/post.ts
  client/src/apis/review.ts
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewContainer.tsx
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewScroll/Review/Review.scss
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewScroll/Review/Review.tsx
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewScroll/ReviewScroll.scss
  client/src/components/Modal/ReviewModal/ReviewContainer/ReviewScroll/ReviewScroll.tsx
  client/src/components/Modal/ReviewModal/ReviewModal.scss
  client/src/components/PostBar/Post/Post.scss
  client/src/components/PostBar/Post/PostBody/PostBody.tsx
  client/src/components/PostBar/PostBar.tsx
  client/src/components/ScrollLoader/ScrollLoader.scss
  client/src/components/ScrollLoader/ScrollLoader.tsx
  client/src/components/TimeStamp/TimeStamp.tsx
  client/src/hooks/usePostInfiniteScroll.tsx
  client/src/hooks/useReviewInfiniteScroll.tsx
  client/src/types/post.ts
  client/src/types/review.ts
Labels: 🎨 Html&css, 🔨 Refactor

#191 리뷰 보기 기능 추가
  client/src/components/Code/Code.scss
  client/src/components/Code/CodeEditor.tsx
  client/src/components/Code/CodeLines.tsx
  client/src/components/Code/CodeTheme.scss
  client/src/components/Code/CodeViewer.tsx
  client/src/components/Modal/ReviewModal/ReviewModal.tsx
  client/src/components/Modal/ReviewModal/ReviewScroll/ReviewScroll.scss
  client/src/components/Modal/WriteModal/WritingForm/WritingForm.scss
  client/src/components/Modal/WriteModal/WritingForm/WritingForm.tsx
  client/src/components/PostBar/Post/PostFooter/ReviewButton/ReviewButton.tsx
Labels: ✨ Feature, 🔨 Refactor

#193 토큰 재발급시 토큰 내부 값을 검사하도록 수정했습니다.
  server/src/domain/auth/access-token.guard.ts
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.service.spec.ts
  server/src/domain/auth/refresh-token.guard.ts
  server/src/domain/post/post.service.spec.ts
Labels: 🐞 BugFix

#195 게시물 삭제 기능을 구현했습니다
  server/src/domain/auth/auth.service.spec.ts
  server/src/domain/likes/likes.service.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/post/post.subscriber.ts
  server/src/exception/unauthorize.exception.ts
  server/src/main.ts
  server/test/auth.e2e-spec.ts
  server/test/post.e2e-spec.ts
Labels: ✨ Feature

#194 feat(FE): 코드 줄을 보내는 로직을 추가하였습니다 (#177)
  client/src/apis/post.ts
  client/src/components/Code/CodeLines.tsx
  client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
  client/src/types/post.ts
  client/src/utils/code.ts
Labels: ✨ Feature

#198 검색할 때 리뷰 개수로 필터링하는 기능을 구현했습니다
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
Labels: ✨ Feature

#200 fix(FE): 새로고침 시 토큰 날라가는 버그 수정 (#199)
  client/src/apis/auth.ts
  client/src/hooks/useOAuthPopup.tsx
Labels: 🐞 BugFix

#201 fix(FE): 리프레쉬 요청 주소 변경 (#199)
  client/src/apis/auth.ts
Labels: 🐞 BugFix

#203 fix(FE): PostScroll 마지막 페이지 확인 후 Spinner 표시하는 기능 누락 수정 (#147)
  client/src/components/PostScroll/PostScroll.tsx
Labels: 🐞 BugFix

#204 feat(FE): refresh 모킹 및 expiresin 숫자로 가공 (#199)
  client/src/apis/interceptors/refresh.ts
  client/src/hooks/useOAuthPopup.tsx
  client/src/mocks/handlers/authHandler.ts
  client/src/mocks/mockData.ts
  client/src/types/auth.ts
Labels: ✨ Feature, 🐞 BugFix

#205 게시물 신고 기능을 구현하고, 많은 에러를 잡았습니다.
  server/src/app.module.ts
  server/src/domain/likes/likes.controller.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.service.ts
  server/src/domain/report/dto/controller-request.dto.ts
  server/src/domain/report/report.controller.ts
  server/src/domain/report/report.entity.ts
  server/src/domain/report/report.module.ts
  server/src/domain/report/report.repository.ts
  server/src/domain/report/report.service.ts
  server/src/domain/review/dto/controller-request.dto.ts
  server/src/domain/review/review.controller.ts
  server/src/domain/review/review.service.ts
  server/src/exception/post-already-reported.exception.ts
  server/src/exception/post-not-reported.exception.ts
  server/src/exception/post-not-written.exception.ts
  server/src/exception/review-not-written.exception.ts
  server/src/main.ts
  server/test/auth.e2e-spec.ts
  server/test/post.e2e-spec.ts
Labels: ✨ Feature

#209 에디터에 중복되는 부분들을 리팩토링합니다.
  client/src/components/Code/CodeContainer.tsx
  client/src/components/Code/CodeEditor.tsx
  client/src/components/Code/CodePresenter.tsx
  client/src/components/Code/CodeViewer.tsx
  client/src/components/Modal/ReviewModal/ReviewModal.tsx
  client/src/components/Modal/WriteModal/WritingForm/WritingForm.tsx
  client/src/components/ScrollLoader/ScrollLoader.scss
  client/src/constants/defaultObject.ts
  client/src/hooks/useEditorScroll.tsx
  client/src/hooks/useHighlight.ts
  client/src/types/post.ts
  client/src/utils/code.ts
  client/src/utils/regExpression.ts
Labels: 🔨 Refactor

#211 useLineNumbers 훅 CodeLines 컴포넌트로 대체 (#208)
  client/src/components/Code/CodeLines.tsx
  client/src/components/Code/CodePresenter.tsx
  client/src/hooks/useLineNumbers.tsx
Labels: 🔨 Refactor

#225 Swagger를 사용해 API 문서를 만들었습니다
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/likes/likes.controller.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/report/report.controller.ts
  server/src/domain/report/report.service.ts
  server/src/domain/review/dto/controller-request.dto.ts
  server/src/domain/review/review.controller.ts
  server/src/exception/token-not-found.exception.ts
  server/src/exception/token-not-permitted.exception.ts
  server/src/exception/unauthorize.exception.ts
  server/src/exception/user-not-same.exception.ts
  server/src/main.ts
Labels: 📬 API

#227 FE stylelint 설정 추가
  client/.stylelintrc.json
  client/package-lock.json
  client/package.json
Labels: ⚙ Setting

#229 모든 scss파일에 StyleLint 적용 (#226)
  client/src/App.scss
  client/src/components/Code/Code.scss
  client/src/components/Code/CodeTheme.scss
  client/src/components/CommonButtons/CommonButtons.scss
  client/src/components/CommonButtons/SvgIconButton/SvgIconButton.scss
  client/src/components/LoadingSpinner/LoadingSpinner.scss
  client/src/components/MainNav/Filter/Filter.scss
  client/src/components/MainNav/MainNav.scss
  client/src/components/MainNav/Menu/Menu.scss
  client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.scss
  client/src/components/MainNav/Profile/Profile.scss
  client/src/components/MainNav/Profile/UserProfile/UserProfile.scss
  client/src/components/Modal/ModalContainer/ModalContainer.scss
  client/src/components/Modal/ModalWrapper/ModalWrapper.scss
  client/src/components/Modal/ReviewModal/ReviewScroll/Review/Review.scss
  client/src/components/Modal/ReviewModal/ReviewScroll/ReviewForm/ReviewForm.scss
  client/src/components/Modal/ReviewModal/ReviewScroll/ReviewScroll.scss
  client/src/components/Modal/SearchModal/SearchForm/SearchForm.scss
  client/src/components/Modal/SearchModal/SearchModal.scss
  client/src/components/Modal/WriteModal/CloseButton/CloseButton.scss
  client/src/components/Modal/WriteModal/SnapShotNav/SnapShotNav.scss
  client/src/components/Modal/WriteModal/SubmitModal/ContentArea/ContentArea.scss
  client/src/components/Modal/WriteModal/SubmitModal/SubmitModal.scss
  client/src/components/Modal/WriteModal/SubmitModal/TagInput/TagInput.scss
  client/src/components/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.scss
  client/src/components/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.scss
  client/src/components/Modal/WriteModal/WritingForm/PrettifyButton/PrettifyButton.scss
  client/src/components/Modal/WriteModal/WritingForm/SubmitButton/SubmitButton.scss
  client/src/components/Modal/WriteModal/WritingForm/WritingForm.scss
  client/src/components/PostScroll/Post/Post.scss
  client/src/components/PostScroll/Post/PostTitle/AuthorProfile/FollowButton/FollowButton.scss
  client/src/constants/_library.scss
  client/src/pages/Main/Main.scss
  client/src/styles/_animation.scss
  client/src/styles/_responsive.scss
Labels: 🎨 Html&css

#230 fix(BE): Swagger에서 refreshToken이 적용되지 않는 이슈 해결 (#228)
  server/src/domain/likes/likes.controller.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/report/report.controller.ts
  server/src/domain/review/review.controller.ts
  server/src/main.ts
Labels: 🐞 BugFix

#231 S3 PreSignedUrl 요청 및 이미지 S3 저장 기능 구현 (#216)
  client/public/progressive-image.jpg
  client/src/apis/auth.ts
  client/src/apis/post.ts
  client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
  client/src/mocks/handlers/authHandler.ts
Labels: ✨ Feature, 📬 API

#235 이미지 업로드 Presigned URL을 생성하는 기능을 구현했습니다. (#232)
  server/package-lock.json
  server/package.json
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/ncp-object-storage.ts
Labels: ✨ Feature

#237 컨트롤러에 swagger 플러그인을 적용했습니다
  server/nest-cli.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/domain/auth/auth.controller.ts
  server/src/domain/likes/likes.controller.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/report/report.controller.ts
  server/src/domain/review/review.controller.ts
  server/src/main.ts
Labels: 📬 API, 🔨 Refactor

#234 PreSignedURL BE 응답 방식 변화 적용 (#216)
  client/index.html
  client/src/App.scss
  client/src/apis/auth.ts
  client/src/apis/post.ts
  client/src/assets/progressive-image.jpg
  client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
  client/src/components/PostScroll/Post/PostFooter/LikeButton/LikeButton.tsx
  client/src/components/PostScroll/Post/PostFooter/MoreButton/MoreButton.tsx
  client/src/components/PostScroll/Post/PostFooter/ReportButton/ReportButton.tsx
  client/src/components/PostScroll/Post/PostFooter/ReviewButton/ReviewButton.tsx
  client/src/components/PostScroll/Post/PostFooter/ShareButton/ShareButton.tsx
  client/src/components/PostScroll/Post/PostImageSlider/PostImageSlider.tsx
  client/src/components/commons/ProgressiveImage/ProgressiveImage.tsx
  client/src/components/commons/SvgIconButton/SvgIconButton.scss
  client/src/components/commons/SvgIconButton/SvgIconButton.tsx
  client/src/hooks/useImageIntersect.ts
  client/src/types/auth.ts
  client/src/types/post.ts
Labels: 📬 API

#239 fix(FE): 변경된 전역 스토어 상태 적용 (#238)
  client/src/apis/post.ts
Labels: 🐞 BugFix

#240 fix(FE): 샘플 데이터를 이용하던 로직에서 생성된 이미지를 이용하도록 변경 (#238)
  client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
Labels: 🐞 BugFix

#241 fix(FE): 전송 환경 초기화 (#238)
  client/src/apis/post.ts
Labels: 🐞 BugFix

#243 fix(FE): pipe 함수로 Promise 객체가 넘어가는 버그 수정 (#238)
  client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
Labels: 🐞 BugFix

#246 TypeORM varchar 길이를 지정했습니다. (#245)
  server/.gitignore
  server/src/domain/image/image.entity.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/report/report.entity.ts
  server/src/domain/tag/tag.entity.ts
  server/src/domain/user/user.entity.ts
Labels: 🐞 BugFix

#244 좋아요 토글 기능 추가 (#215)
  client/src/apis/post.ts
  client/src/components/PostScroll/Post/PostFooter/LikeButton/LikeButton.tsx
  client/src/hooks/usePostLike.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/types/post.ts
Labels: ✨ Feature

#251 refactor(FE): Style 변경 미반영 컴포넌트 반영 (#220)
  client/src/App.scss
  client/src/components/main/Modal/ReviewModal/ReviewModal.scss
  client/src/components/main/Modal/SearchModal/SearchForm/SearchLabel/SearchLabel.scss
  client/src/components/main/Modal/SearchModal/SearchForm/SearchLabel/SearchLabel.tsx
  client/src/components/main/Modal/SearchModal/SearchModal.scss
  client/src/components/main/Modal/WriteModal/WriteModal.scss
  client/src/components/main/Modal/WriteModal/WriteModal.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.scss
  client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/SubmitButton/SubmitButton.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/WritingForm.tsx
  client/src/pages/Main/Main.scss
  client/src/pages/Main/Main.tsx
Labels: 🎨 Html&css

#253 서비스 레이어에서 에러를 제거했습니다. (#248)
  server/src/domain/auth/auth.controller.ts
  server/src/domain/auth/ncp-object-storage.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/report/report.controller.ts
  server/src/domain/report/report.service.ts
  server/src/domain/review/review.controller.ts
  server/src/domain/review/review.service.ts
  server/src/exception/post-not-written.exception.ts
  server/src/exception/review-not-written.exception.ts
Labels: 🔨 Refactor
