Repository boostcampwm-2022/web06-weview, pull requests merged in 2022-12, with the labels that each got.

#259 ci(BE): 실서버 자동배포 설정 (#258)
  .github/workflows/client-integration.yml
  .github/workflows/dev-client-deploy.yml
  .github/workflows/dev-server-deploy.yml
  .github/workflows/main-client-deploy.yml
  .github/workflows/main-server-deploy.yml
  .github/workflows/server-integration.yml
  client/package.json
  server/package.json
Labels: 🌏 Deploy

#261 ci(DO): 환경변수 이름 수정 (#258)
  .github/workflows/dev-client-deploy.yml
Labels: 🌏 Deploy

#262 dev브랜치 action에 있었던 버그 수정
  .github/workflows/dev-client-deploy.yml
Labels: 🌏 Deploy

#263 도커 이미지 태그를 변경했습니다. (#258)
  .github/workflows/main-server-deploy.yml
Labels: 🌏 Deploy

#267 쿠키 secure 설정
  server/src/domain/auth/auth.controller.ts
Labels: ✨ Feature

#268 feat(BE): 쿠키 secure 설정 (#258)
  server/src/domain/auth/auth.controller.ts
Labels: 🐞 BugFix

#269 NCP 오브젝트 스토리지 버킷명 환경변수화
  server/src/domain/auth/ncp-object-storage.ts
Labels: 🌏 Deploy

#270 도커 이미지에 latest 태그를 추가했습니다. (#258)
  .github/workflows/main-server-deploy.yml
Labels: 🌏 Deploy

#277 FE 인기 검색 태그
  client/package.json
  client/src/apis/ranking.ts
  client/src/components/main/TagRanking/TagRanking.scss
  client/src/components/main/TagRanking/TagRanking.tsx
  client/src/components/main/TagRanking/TagRankingItem/TagRankingItem.scss
  client/src/components/main/TagRanking/TagRankingItem/TagRankingItem.tsx
  client/src/hooks/useRanking.ts
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/rankingHandler.ts
  client/src/pages/Main/Main.tsx
  client/src/react-query/queryKeys.ts
  client/src/styles/_theme.scss
  client/src/types/ranking.ts
Labels: ✨ Feature, 🎨 Html&css

#284 scheduler server에 ci/cd를 적용했습니다
  .github/workflows/dev-scheduler-server-deploy.yml
  .github/workflows/main-scheduler-server-deploy.yml
  .github/workflows/scheduler-server-integration.yml
  scheduler-server/Dockerfile
Labels: 🌏 Deploy

#285 설정 파일 오타 수정
  .github/workflows/dev-scheduler-server-deploy.yml
Labels: 🐞 BugFix

#287 스케쥴러 서버에 Swagger를 적용했습니다
  scheduler-server/package.json
  scheduler-server/src/main.ts
  scheduler-server/src/ranking/dto/controller-request.dto.ts
  scheduler-server/src/ranking/ranking.controller.ts
Labels: ✨ Feature

#288 Ranking 서버의 RankingController url를 변경했습니다
  scheduler-server/src/ranking/ranking.controller.ts
Labels: 📬 API

#300 특정 사용자의 게시물을 조회하는 기능을 구현했습니다
  server/src/app.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/user/dto/controller-request.dto.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.module.ts
  server/src/domain/user/user.service.spec.ts
  server/src/domain/user/user.service.ts
Labels: ✨ Feature

#298 검색 API 명세 변경에 따라 로직을 수정했습니다.
  server/src/domain/post/category.ts
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/service-request.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/search/dto/controller-response.dto.ts
  server/src/domain/search/search-history.mongo.repository.ts
  server/src/domain/search/search-history.mongo.ts
  server/src/domain/user/user.service.ts
  server/test/post.e2e-spec.ts
Labels: 📬 API, 🔨 Refactor

#302 FE 최근 검색 목록 불러오기 및 사용하는 기능 추가 (#280)
  client/src/apis/post.ts
  client/src/apis/search.ts
  client/src/assets/images/labels/label-comment.svg
  client/src/assets/images/labels/label-detail.svg
  client/src/assets/images/labels/label-like.svg
  client/src/assets/images/labels/label-tag.svg
  client/src/components/commons/LoadingSpinner/LoadingSpinner.scss
  client/src/components/commons/LoadingSpinner/LoadingSpinner.tsx
  client/src/components/commons/SearchLabel/SearchLabel.scss
  client/src/components/commons/SearchLabel/SearchLabel.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContent.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContent.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentBody.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentHistory.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
  client/src/constants/search.ts
  client/src/hooks/useLabel.ts
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/handlers/rankingHandler.ts
  client/src/mocks/handlers/reviewHandler.ts
  client/src/mocks/handlers/searchHandler.ts
  client/src/mocks/utils/mockUtils.ts
  client/src/react-query/queryKeys.ts
  client/src/styles/_mixin.scss
  client/src/styles/_theme.scss
  client/src/types/post.ts
  client/src/types/react-query.ts
  client/src/types/search.ts
  client/src/utils/label.ts
  client/src/utils/queryString.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#304 최근 검색어 명세 일치 오류 수정
  client/src/apis/search.ts
  client/src/mocks/handlers/searchHandler.ts
Labels: 🐞 BugFix

#308 fix(BE): 검색 기록이 API 명세와 맞지 않는 오류 수정 (#303)
  server/src/domain/user/user.controller.ts
Labels: 🐞 BugFix

#310 Fix/#303 search history deploy
  client/src/mocks/utils/mockUtils.ts
  client/src/utils/queryString.ts
Labels: 🐞 BugFix

#312 feat(FE): 최근 검색 기록 최대 5개만 가져오기, 기록 제거 버튼 기능 구현 (#280)
  client/src/apis/search.ts
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
  client/src/constants/search.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/handlers/searchHandler.ts
  client/src/types/search.ts
Labels: ✨ Feature

#315 fix(BE): 상세 검색시 각 검색어가 AND 연산이 일어나도록 수정 (#314)
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#318 게시물 단건 조회 기능을 구현했습니다.
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/user/user.controller.ts
Labels: ✨ Feature

#320 fix(BE): 오탈자로 인한 오류 해결 (#317)
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#324 북마크 목록, 추가, 삭제 기능을 구현했습니다.
  server/src/app.module.ts
  server/src/domain/bookmark/bookmark.controller.ts
  server/src/domain/bookmark/bookmark.entity.ts
  server/src/domain/bookmark/bookmark.module.ts
  server/src/domain/bookmark/bookmark.repository.ts
  server/src/domain/bookmark/bookmark.service.ts
  server/src/domain/bookmark/dto/controller-request.dto.ts
  server/src/domain/user/user.controller.ts
  server/src/exception/bookmark-not-found.exception.ts
  server/src/exception/post-already-bookmarked.exception.ts
Labels: ✨ Feature

#325 북마크 목록 isLast 로직 수정
  server/src/domain/bookmark/bookmark.service.ts
Labels: ✨ Feature

#327 글 목록 정보에 북마크 여부를 추가했습니다.
  server/src/domain/bookmark/bookmark.service.ts
  server/src/domain/post/dto/service-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.module.ts
Labels: ✨ Feature

#326 게시글 공유 기능 추가
  client/src/ReactRouter.tsx
  client/src/apis/post.ts
  client/src/components/main/MainNav/NavHeader/NavHeader.tsx
  client/src/components/main/PostScroll/Post/PostFooter/LeftBlockItems/ShareButton.tsx
  client/src/mocks/handlers/postHandler.ts
  client/src/pages/Post/Post.scss
  client/src/pages/Post/Post.tsx
Labels: ✨ Feature

#328 FE 북마크 관련 기능 추가, MOCK API 환경 완성 (#293)
  client/src/apis/bookmark.ts
  client/src/apis/post.ts
  client/src/components/commons/SvgIconButton/SvgIconButton.scss
  client/src/components/main/MainNav/NavHeader/NavHeader.tsx
  client/src/components/main/MainNav/NavMenus/BookmarkMenu/BookmarkMenu.tsx
  client/src/components/main/PostScroll/Post/PostFooter/LeftBlockItems/BookmarkButton.tsx
  client/src/components/main/PostScroll/Post/PostFooter/PostFooter.tsx
  client/src/hooks/useBookmark.ts
  client/src/hooks/useNav.ts
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/authHandler.ts
  client/src/mocks/handlers/bookmarkHandler.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/mocks/mockData.ts
  client/src/store/useSearchStore.ts
  client/src/types/post.ts
Labels: ✨ Feature

#329 글쓰기 모달 관련 디테일한 작업
  client/src/App.scss
  client/src/components/main/CodeEditor/CodeEditor.scss
  client/src/components/main/CodeEditor/CodeEditor.tsx
  client/src/components/main/MainNav/NavHeader/NavHeader.tsx
  client/src/hooks/useEditorScroll.ts
  client/src/styles/_mixin.scss
Labels: 🎨 Html&css

#332 스케쥴러 서버에 빈 배열을 요청보낼 때 예외를 처리했습니다.
  server/src/domain/post/post.controller.ts
Labels: 🐞 BugFix

#335 API 명세에 맞춰 단건 조회 시 post를 감싸서 보내도록 변경했습니다.
  server/src/domain/post/post.controller.ts
Labels: 🐞 BugFix, 📬 API

#333 FE 상세 검색 (좋아요 수, 리뷰 수) 구현 (#289)
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContent.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
  client/src/constants/search.ts
  client/src/hooks/useLabel.ts
  client/src/mocks/utils/mockUtils.ts
  client/src/store/useLabelStore.ts
  client/src/styles/_mixin.scss
Labels: ✨ Feature

#341 fix(FE): 첫번째 refresh된 요청에 헤더 안 붙는 에러 수정 (#339)
  client/src/hooks/useRefreshInterceptor.ts
Labels: 🐞 BugFix

#342 북마크 게시물 작성자가 자신으로 설정되는 오류를 수정했습니다.
  server/src/domain/bookmark/bookmark.repository.ts
  server/src/domain/bookmark/bookmark.service.ts
Labels: 🐞 BugFix

#348 fix(BE): 검색시 최근 검색어 저장 기능 동기화 (#347)
  server/src/domain/post/post.controller.ts
  server/src/domain/search/search-history.mongo.repository.ts
  server/src/domain/user/user.service.ts
Labels: 🐞 BugFix

#357 fix(FE): Search 요청이 완료된 이후 History 요청이 되지 않던 오류 해결 (#347)
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/mocks/handlers/searchHandler.ts
Labels: 🐞 BugFix

#360 공유하기 부분 에러 수정
  client/src/hooks/useBookmark.ts
  client/src/hooks/useLabel.ts
  client/src/hooks/usePostLike.ts
  client/src/pages/Post/Post.scss
  client/src/pages/Post/Post.tsx
Labels: 🐞 BugFix

#362 글 상세 조회, 북마크 글 목록 API에서 좋아요/북마크 여부 표시
  server/src/domain/bookmark/bookmark.module.ts
  server/src/domain/bookmark/bookmark.service.ts
  server/src/domain/likes/likes.service.ts
  server/src/domain/post/post.controller.ts
Labels: ✨ Feature

#365 공용 모달 컴포넌트 생성 및 더보기 모달에 삭제 기능 연동 (#351)
  client/index.html
  client/src/App.tsx
  client/src/apis/post.ts
  client/src/components/commons/Modal/ModalProvider/ModalProvider.tsx
  client/src/components/commons/Modal/core/Modal/Modal.tsx
  client/src/components/commons/Modal/core/ModalContainer/ModalContainer.tsx
  client/src/components/commons/Modal/core/ModalContents/ModalContents.scss
  client/src/components/commons/Modal/core/ModalContents/ModalContents.tsx
  client/src/components/commons/Modal/core/ModalOverlay/ModalOverlay.scss
  client/src/components/commons/Modal/core/ModalOverlay/ModalOverlay.tsx
  client/src/components/commons/Modal/core/ModalTitle/ModalTitle.scss
  client/src/components/commons/Modal/core/ModalTitle/ModalTitle.tsx
  client/src/components/commons/Modal/core/ModalWrapper/ModalWrapper.scss
  client/src/components/commons/Modal/core/ModalWrapper/ModalWrapper.tsx
  client/src/components/main/Modal/WriteModal/CloseButton/CloseButton.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/CloseButton/CloseButton.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/SubmitModal.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/SubmitButton/SubmitButton.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/WritingForm.tsx
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/MoreButton.tsx
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModal.scss
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModal.tsx
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModalMenu/PostMoreModalMenu.scss
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModalMenu/PostMoreModalMenu.tsx
  client/src/hooks/useModal.ts
  client/src/hooks/useOutsideClickHandler.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Post/Post.tsx
  client/src/store/useModalStore.ts
  client/src/store/useWritingModalStore.ts
  client/src/types/modal.ts
Labels: ✨ Feature

#373 인기 태그 레이아웃 수정 및 줄 수 탭 기능 추가
  client/src/App.scss
  client/src/components/main/CodeEditor/CodeEditor.tsx
  client/src/components/main/Modal/ReviewModal/ReviewModal.tsx
  client/src/hooks/useCodeEditor.ts
Labels: ✨ Feature, 🎨 Html&css

#384 게시물 단건 조회 시 API를 변경했습니다.
  server/src/domain/post/dto/controller-request.dto.ts
  server/src/domain/post/dto/controller-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/user/dto/controller-request.dto.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.service.spec.ts
  server/src/domain/user/user.service.ts
Labels: 🔨 Refactor

#375 fix(FE): 북마크 낙관적 업데이트가 페이지 전환 시 되지 않던 오류 수정 (#346)
  client/src/apis/post.ts
  client/src/components/main/PostScroll/Post/PostFooter/LeftBlockItems/BookmarkButton.tsx
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/MoreButton.tsx
  client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModal.tsx
  client/src/hooks/useBookmark.ts
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/hooks/usePostLike.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/pages/Post/Post.tsx
  client/src/store/useSearchStore.ts
  client/src/types/modal.ts
  client/src/types/search.ts
Labels: 🐞 BugFix

#388 변경된 DTO 사양이 반영되지 않은 테스트 코드를 비활성화했습니다.
  server/src/domain/post/post.service.spec.ts
Labels: ✅ Test

#389 reusable workflow로 클라이언트, 서버의 배포 공통 로직을 각각 분리했습니다.
  .github/workflows/deployment-dev-api-server.yml
  .github/workflows/deployment-dev-client.yml
  .github/workflows/deployment-dev-scheduler-server.yml
  .github/workflows/deployment-main-api-server.yml
  .github/workflows/deployment-main-client.yml
  .github/workflows/deployment-main-scheduler-server.yml
  .github/workflows/dev-scheduler-server-deployment.yml
  .github/workflows/dev-server-deployment.yml
  .github/workflows/integration-api-server.yml
  .github/workflows/integration-client.yml
  .github/workflows/integration-scheduler-server.yml
  .github/workflows/main-client-deployment.yml
  .github/workflows/main-scheduler-server-deployment.yml
  .github/workflows/main-server-deployment.yml
  .github/workflows/reusable-deployment-client.yml
  .github/workflows/reusable-deployment-server.yml
  scheduler-server/package-lock.json
Labels: 🌏 Deploy, 🔨 Refactor

#390 CI에 reusable workflow를 적용하고, Github actions 캐싱을 적용했습니다.
  .github/workflows/integration-api-server.yml
  .github/workflows/integration-client.yml
  .github/workflows/integration-scheduler-server.yml
  .github/workflows/reusable-deployment-client.yml
  .github/workflows/reusable-deployment-server.yml
  .github/workflows/reusable-integration.yml
Labels: 🌏 Deploy, 🔨 Refactor

#387 스냅샷 관련 기능 추가
  client/src/components/main/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.tsx
  client/src/components/main/Modal/WriteModal/WritingForm/WritingForm.tsx
  client/src/hooks/useCodeEditor.ts
  client/src/hooks/useSnapshotCodeBlock.ts
  client/src/store/useCodeEditorStore.ts
  client/src/utils/async.ts
Labels: ✨ Feature, 🐞 BugFix

#394 fix(BE): 도커 컨테이너에 timezone 패키지 설치 (#363)
  scheduler-server/Dockerfile
  server/Dockerfile
Labels: 🐞 BugFix

#399 fix(DO): 서버 reusable workflow 파일 내 오타 수정 (#398)
  .github/workflows/reusable-deployment-server.yml
Labels: 🐞 BugFix

#397 design(FE): 모달 배경 레이아웃 통일 및 믹스인 분리 (#381)
  client/src/components/commons/Modal/core/ModalOverlay/ModalOverlay.scss
  client/src/components/main/Modal/ModalWrapper/ModalWrapper.scss
  client/src/styles/_mixin.scss
Labels: 🎨 Html&css

#404 인기 태그를 24시간동안 유지하도록 변경했습니다.
  scheduler-server/src/ranking/ranking.service.ts
Labels: ✨ Feature

#403 hashFiles 문법 오류로 작은따옴표로 변경했습니다.
  .github/workflows/reusable-deployment-client.yml
Labels: 🐞 BugFix

#406 design(FE): 불필요한 gap 속성으로 인한 밀림 수정 (#396)
  client/src/pages/Main/Main.scss
Labels: 🐞 BugFix

#408 클라이언트 CD 파일의 secrets 변수명 틀린 오류 수정
  .github/workflows/reusable-deployment-client.yml
Labels: 🌏 Deploy

#405 게시글에 태그 정보를 보여주는 기능 추가 (#353)
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
  client/src/components/main/PostScroll/Post/PostBody/PostBody.scss
  client/src/components/main/PostScroll/Post/PostBody/PostBody.tsx
  client/src/components/main/PostScroll/Post/PostBody/PostContent/PostContent.scss
  client/src/components/main/PostScroll/Post/PostBody/PostContent/PostContent.tsx
  client/src/components/main/PostScroll/Post/PostBody/PostTags/PostTags.scss
  client/src/components/main/PostScroll/Post/PostBody/PostTags/PostTags.tsx
  client/src/hooks/useLabel.ts
  client/src/mocks/datasource/mockDataSource.ts
Labels: ✨ Feature

#409 클라이언트 secrets에 VITE 누락 수정
  .github/workflows/deployment-dev-client.yml
  .github/workflows/deployment-main-client.yml
Labels: 🌏 Deploy, 🐞 BugFix

#412 fix(FE): URL에 해시태그가 있을 경우 주석처리되는 오류 해결 및 Mock 테스트 추가 (#410)
  client/src/hooks/useLabel.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/utils/queryString.ts
Labels: 🐞 BugFix

#411 fix(BE): 삭제된 글이 북마크, 내 글 목록에 보이는 오류 수정 및 북마크 lastId 적용 (#380)
  server/src/domain/bookmark/bookmark.repository.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.module.ts
Labels: 🐞 BugFix

#413 providers가 누락되어 수정했습니다.
  server/src/domain/user/user.module.ts
Labels: 🐞 BugFix

#416 조회된 글이 없을 때 진행사항 보여주기 및 다른 검색어 유도
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
  client/src/components/main/PostScroll/NoPost/NoPost.scss
  client/src/components/main/PostScroll/NoPost/NoPost.tsx
  client/src/components/main/PostScroll/PostScroll.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#402 엘라스틱서치를 적용했습니다.
  server/package-lock.json
  server/package.json
  server/src/domain/image/image.entity.ts
  server/src/domain/image/image.repository.ts
  server/src/domain/likes/likes.service.ts
  server/src/domain/post/dto/controller-response.dto.ts
  server/src/domain/post/dto/service-request.dto.ts
  server/src/domain/post/post-search.service.spec.ts
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.module.ts
  server/src/domain/post/post.repository.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/domain/post/types/post-search-body.interface.ts
  server/src/domain/review/review.service.ts
  server/src/exception/post-input-invalid.exception.ts
  server/src/exception/search-param-invalid.exception.ts
  server/src/exception/search-response-invalid.exception.ts
  server/src/exception/tag-invalid.exception.ts
Labels: 🔨 Refactor

#424 이미지 슬라이더 추가
  client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.scss
  client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.tsx
  client/src/components/main/PostScroll/Post/PostImageSlider/SlideButton/SlideButton.scss
  client/src/components/main/PostScroll/Post/PostImageSlider/SlideButton/SlideButton.tsx
  client/src/constants/style.ts
  client/src/mocks/datasource/mockDataSource.ts
  client/src/utils/style.ts
Labels: ✨ Feature, 🎨 Html&css

#429 CI와 CD 파일을 각각 통합했습니다.
  .github/workflows/deployment-dev-api-server.yml
  .github/workflows/deployment-dev-client.yml
  .github/workflows/deployment-dev-scheduler-server.yml
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-main-api-server.yml
  .github/workflows/deployment-main-client.yml
  .github/workflows/deployment-main-scheduler-server.yml
  .github/workflows/deployment-main.yml
  .github/workflows/integration-api-server.yml
  .github/workflows/integration-client.yml
  .github/workflows/integration-scheduler-server.yml
  .github/workflows/integration.yml
Labels: 🌏 Deploy, 🔨 Refactor

#423 랭킹 오류를 해결하고 랭킹에 시간 가중치를 적용했습니다.
  scheduler-server/src/ranking/ranking.controller.ts
  scheduler-server/src/ranking/ranking.service.ts
Labels: ✨ Feature

#430 yaml 문법을 수정했습니다.
  .github/workflows/deployment-main.yml
Labels: 🌏 Deploy, 🐞 BugFix

#428 결과값이 내림차순으로 정렬되지 않는 이슈를 해결하였습니다.
  server/src/domain/post/post-search.service.spec.ts
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/types/post-search-body.interface.ts
Labels: 🐞 BugFix

#431 paths filter 비교 대상이 이상한 오류 수정
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-main.yml
  .github/workflows/integration.yml
Labels: 🐞 BugFix

#427 슬라이더 dots 투명도 설정 및 모바일 슬라이딩 기능 구현
  client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.scss
  client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.tsx
  client/src/utils/style.ts
Labels: ✨ Feature, 🎨 Html&css

#435 fix(BE): 검색이 이상하게 되는 경우들을 수정하였습니다 -2차
  server/src/domain/post/dto/controller-response.dto.ts
  server/src/domain/post/post.controller.ts
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#439 검색 콘텐츠 UI/UX 개선 - 1 (#355)
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
  client/src/components/main/MainNav/NavHeader/NavHeader.tsx
  client/src/components/main/PostScroll/NoPost/NoPost.tsx
  client/src/components/main/PostScroll/Post/PostBody/PostTags/PostTags.tsx
  client/src/hooks/useLabel.ts
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/hooks/useSearch.ts
  client/src/store/useLabelStore.ts
  client/src/styles/_animation.scss
  client/src/styles/_mixin.scss
  client/src/utils/label.ts
Labels: ✨ Feature

#443 엘라스틱서치 변경 후 Post가 삭제되지 않는 이슈를 해결하였습니다.
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
Labels: 🐞 BugFix

#444 feat(FE): 포스트 목록 스켈레톤 UI 적용 (#291)
  client/src/components/main/PostScroll/Post/PostTitle/PostTitle.scss
  client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.scss
  client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.tsx
  client/src/components/main/TagRanking/TagRankingSkeletonItem/TagRankingSkeletonItem.scss
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Post/Post.tsx
  client/src/styles/_animation.scss
  client/src/styles/_mixin.scss
  client/src/styles/_theme.scss
Labels: ✨ Feature

#445 fix(FE): 메뉴 버튼 클릭 시 / 로 네비게이션 되도록 오류 수정 (#420)
  client/src/hooks/useNav.ts
Labels: 🐞 BugFix

#449 fix(FE): 미인증 상태에서 로그인 클릭 시 401 응답으로 출력하는 오류 수정 (#420)
  client/src/components/main/MainNav/NavMenus/BookmarkMenu/BookmarkMenu.tsx
  client/src/hooks/useAuth.ts
Labels: 🐞 BugFix

#451 fix(BE): 태그들을 각 배열의 원소로 분리 (#450)
  server/src/domain/post/dto/controller-response.dto.ts
Labels: 🐞 BugFix

#457 실서버에 v1.0.2 버전을 배포합니다.
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-main.yml
  .github/workflows/integration.yml
  README.md
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.scss
  client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
  client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
  client/src/components/main/MainNav/NavHeader/NavHeader.tsx
  client/src/components/main/MainNav/NavMenus/BookmarkMenu/BookmarkMenu.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/ContentArea/ContentArea.scss
  client/src/components/main/Modal/WriteModal/SubmitModal/ContentArea/ContentArea.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.scss
  client/src/components/main/Modal/WriteModal/SubmitModal/SubmitModal.scss
  client/src/components/main/Modal/WriteModal/SubmitModal/SubmitModal.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.scss
  client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.tsx
  client/src/components/main/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.scss
  client/src/components/main/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.tsx
  client/src/components/main/PostScroll/NoPost/NoPost.tsx
  client/src/components/main/PostScroll/Post/PostBody/PostTags/PostTags.tsx
  client/src/components/main/PostScroll/Post/PostTitle/PostTitle.scss
  client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.scss
  client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.tsx
  client/src/components/main/TagRanking/TagRankingSkeletonItem/TagRankingSkeletonItem.scss
  client/src/hooks/useAuth.ts
  client/src/hooks/useLabel.ts
  client/src/hooks/useNav.ts
  client/src/hooks/usePostInfiniteScroll.ts
  client/src/hooks/useSearch.ts
  client/src/mocks/handlers/postHandler.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Post/Post.tsx
  client/src/store/useLabelStore.ts
  client/src/styles/_animation.scss
  client/src/styles/_mixin.scss
  client/src/styles/_theme.scss
  client/src/utils/label.ts
  server/src/domain/post/dto/controller-response.dto.ts
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/post.service.spec.ts
  server/src/domain/post/post.service.ts
  server/src/main.ts
Labels: 🌏 Deploy

#459 리뷰와 신고 서비스의 단위 테스트를 작성했습니다.
  scheduler-server/src/ranking/ranking.service.ts
  server/package.json
  server/src/domain/report/report.service.spec.ts
  server/src/domain/review/review.service.spec.ts
Labels: ✅ Test

#463 docs(DO): Wiki 링크 오타 수정, 프로필 이미지 링크 수정 (#462)
  README.md
Labels: 📃 Docs

#464 실서버에 v1.0.4 버전을 배포합니다.
  README.md
Labels: 🌏 Deploy

#466 좋아요, 리뷰 개수로 검색이 가능하지 않던 이슈 해결하였습니다.
  server/src/domain/post/post-search.service.spec.ts
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.repository.ts
Labels: 🐞 BugFix

#468 실서버에 v1.0.5 배포 (#467)
  server/src/domain/post/post-search.service.spec.ts
  server/src/domain/post/post-search.service.ts
  server/src/domain/post/post.entity.ts
  server/src/domain/post/post.repository.ts
Labels: 🌏 Deploy, 🐞 BugFix
